language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t afiqon/travis_ci -f Dockerfile.dev .

script:
    - docker run afiqon/travis_ci npm run test -- --coverage